spring:
  profiles:
    active: @build.profile.active@
server:
  port: 8080
  servlet:
    context-path: /my-spring-demo

jwt:
  secret: mysecret
  expire: 120000
  token-header: Authorization

mybatis:
  type-aliases-package: com.example.myspringdemo.entity
  configuration:
    map-underscore-to-camel-case: true