spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://192.168.2.8:3306/test?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf8
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave1:
      jdbc-url: jdbc:mysql://192.168.2.9:3306/test?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf8
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave2:
      jdbc-url: jdbc:mysql://192.168.2.10:3306/test?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf8
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver